### ISSUE TITLE
D:\Desktop\PhasmophobiaCheat-main\Inject & launcher\Inject & launcher.csproj : error  : The SDK 'Microsoft.NET.Sdk' specified could not be found.  D:\Desktop\PhasmophobiaCheat-main\Inject & launcher\Inject & launcher.csproj

### ISSUE THREAD

**Issue by EASBLOX** [issuimo/PhasmophobiaCheat#1]

**Comment by issuimo** [comment]
请在VS工作负载中安装.NET 8.0组件

**Comment by EASBLOX** [comment]
不管用

D:\Desktop\PhasmophobiaCheat-main\Inject & launcher\Inject & launcher.csproj : error  : The SDK 'Microsoft.NET.Sdk' specified could not be found.  D:\Desktop\PhasmophobiaCheat-main\Inject & launcher\Inject & launcher.csproj

D:\Desktop\PhasmophobiaCheat-main\Phasmophobia\Phasmophobia.vcxproj : warning  : The build tools for Intel C++ Compiler 2023 cannot be found. Install Intel C++ Compiler 2023 to build using the Intel C++ Compiler 2023 build tools.

D:\Desktop\PhasmophobiaCheat-main\Inject & launcher\Inject & launcher.csproj : error  : The SDK 'Microsoft.NET.Sdk' specified could not be found.  D:\Desktop\PhasmophobiaCheat-main\Inject & launcher\Inject & launcher.csproj

**Comment by EASBLOX** [comment]
能給個下載鏈接嗎，不知道有沒有下載錯

**Comment by issuimo** [comment]
#5

**Comment by issuimo** [comment]
D:\Desktop\PhasmophobiaCheat-main\Phasmophobia\Phasmophobia.vcxproj : warning : The build tools for Intel C++ Compiler 2023 cannot be found. Install Intel C++ Compiler 2023 to build using the Intel C++ Compiler 2023 build tools.
使用最新版本即可解决

D:\Desktop\PhasmophobiaCheat-main\Inject & launcher\Inject & launcher.csproj : error : The SDK 'Microsoft.NET.Sdk' specified could not be found. D:\Desktop\PhasmophobiaCheat-main\Inject & launcher\Inject & launcher.csproj
[Link](https://learn.microsoft.com/en-us/answers/questions/1184941/the-sdk-microsoft-net-sdk-specified-could-not-be-f)
