### ISSUE TITLE
Visual Studio errors

### ISSUE THREAD

**Issue by Chubbbs** [issuimo/PhasmophobiaCheat#2]
So when I open the project and build it throws a bunch of errors, example:

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'BOOL SetConsoleTitleA(LPCSTR)': cannot convert argument 1 from 'const wchar_t *' to 'LPCSTR' (compiling source file features\Ghost.cpp)	Phasmophobia	C:\Users\user\Desktop\PhasmophobiaCheat-main\Phasmophobia\library\Console.hpp	87	

Would love to have this to practice and learn with.

**Comment by issuimo** [comment]
You can try changing SetConsoleTitle to SetConsoleTitleW, or change the character set to Unicode in the project properties page.
