### ISSUE TITLE
Where did you get structs from?

### ISSUE THREAD

**Issue by Random-Cod3r** [issuimo/PhasmophobiaCheat#4]
ex unity::Il2cpp::Method::GetAddress("GhostAI", "Hunting", 3)),

Like where did you find the class for ghostai

**Comment by Random-Cod3r** [comment]
Do you have a list of deobfuscated structs and classes?

**Comment by issuimo** [comment]
The structure is from a dump file, and the dump tool is https://github.com/Perfare/Zygisk-Il2CppDumper.

**Comment by Random-Cod3r** [comment]
> The structure is from a dump file, and the dump tool is https://github.com/Perfare/Zygisk-Il2CppDumper.

Does it auto do this I know in the sln in UnityHack.h there is stuff about dump.cs etc?

**Comment by issuimo** [comment]
> > The structure is from a dump file, and the dump tool is https://github.com/Perfare/Zygisk-Il2CppDumper.
> 
> Does it auto do this I know in the sln in UnityHack.h there is stuff about dump.cs etc?

There is no content about "dump.cs" in UnityHack.h. It is just a C++ library that retrieves game function information during runtime.
