### ISSUE TITLE
mkl.h

### ISSUE THREAD

**Issue by orcun9988** [issuimo/PhasmophobiaCheat#5]
can u add to your guide how to install intel kernel libary for windows  "mkl.h" ?

![err](https://github.com/issuimo/PhasmophobiaCheat/assets/58307867/4178e200-d790-4f9c-a8d1-2c96af047150)

**Comment by issuimo** [comment]
In fact, MKL is not necessary. If you want to use MKL, you can download the Intel oneAPI Base Toolkit from [oneapi](https://www.intel.com/content/www/us/en/developer/tools/oneapi/toolkits.html).
