### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by orcun9988** [issuimo/PhasmophobiaCheat#6]
![image](https://github.com/issuimo/PhasmophobiaCheat/assets/58307867/2d346fda-b5e9-4560-83b3-68edc104fed2)
that button "Intereact" won't work
` public static void Interact()
 {
     Debug.Msg("Troll->Interact: Triggered", 1);
   //   Main.ghostAI.Inte();
     Main.ghostActivity.Interact();

     Main.ghostAI.field_Public_GhostActivity_0.InteractWithARandomProp(true,true);
     Main.ghostAI.field_Public_GhostActivity_0.Interact();
     Main.ghostAI.field_Public_GhostActivity_0.InteractWithARandomDoor();
 }`

add item won't work

When u press DELETE key it should appear mouse visitibly but there is no
`  if (cheatmenu == false)
  {
      cheatmenu = true;
      originalLockState = Cursor.lockState;
      originalVisible = Cursor.visible;
      Cursor.lockState = CursorLockMode.None;
      Cursor.visible = true;
      if (myPlayer != null)
          myPlayer.field_Public_FirstPersonController_0.enabled = false;
  }
  else if (cheatmenu == true)
  {
      cheatmenu = false;
      Cursor.lockState = originalLockState;
      Cursor.visible = originalVisible;
      if (myPlayer != null)
          myPlayer.field_Public_FirstPersonController_0.enabled = true;`

also I suggesting add

RandomWeather -> public void PlayLightningEffect()
and noclip & fly
`    fly = !fly;
    if (fly)
    {
        GetLocalPlayer().field_Public_CharacterController_0.enabled = false;
        GetLocalPlayer().GetComponent<Rigidbody>().useGravity = false;
    }
    else
    {
        GetLocalPlayer().GetComponent<Collider>().enabled = true;
    }
}
if (fly)
{
    Ray y = Camera.main.ScreenPointToRay(new Vector2(Screen.width / 2, Screen.height / 2));
    float up = y.direction.y * movementMultiplier * Time.deltaTime;
    float frd = (Mathf.Abs(y.direction.z) + Mathf.Abs(y.direction.x)) / 2;
    GetLocalPlayer().field_Public_CharacterController_0.enabled = false;
    GetLocalPlayer().GetComponent<Rigidbody>().useGravity = false;

    if (keyboard.wKey.isPressed)
    {
        GetLocalPlayer().transform.position += GetLocalPlayer().transform.TransformDirection(0, up, frd * movementMultiplier * Time.deltaTime);
    }
    if (keyboard.sKey.isPressed)
    {
        GetLocalPlayer().transform.position += GetLocalPlayer().transform.TransformDirection(0, -(up), -(frd) * movementMultiplier * Time.deltaTime);
    }
    if (keyboard.aKey.isPressed)
    {
        GetLocalPlayer().transform.position += GetLocalPlayer().transform.TransformDirection(-1f * movementMultiplier * Time.deltaTime, 0, 0);
    }
    if (keyboard.dKey.isPressed)
    {
        GetLocalPlayer().transform.position += GetLocalPlayer().transform.TransformDirection(1f * movementMultiplier * Time.deltaTime, 0, 0);
    }
}`

FullBright:
`
                if (keyboard.f1Key.wasPressedThisFrame)
                {
                    CheatToggles.enableFullbright = !CheatToggles.enableFullbright;
                    Debug.Msg("Fullbright: Toggled " + (CheatToggles.enableFullbright ? "On" : "Off"), 1);
                    if (CheatToggles.enableFullbright == true)
                    {
                        Fullbright.Enable();
                    }
                    else
                    {
                        Fullbright.Disable();
                    }
                }

 public static void Enable()
 {
     if (Main.boneTransform != null && Main.initializedScene > 1 && isAlreadyOn == false)
     {
         isAlreadyOn = true;
         Debug.Msg("isAlreadyOn: true", 3);
         Main.light = Main.boneTransform.GetComponent<Light>();
         Object.Destroy(Main.boneTransform.GetComponent<Light>());
         Main.light = Main.boneTransform.gameObject.AddComponent<Light>();
         Main.light.color = Color.white;
         Main.light.type = LightType.Spot;
         Main.light.shadows = LightShadows.None;
         Main.light.range = 99f;
         Main.light.spotAngle = 9999f;
         Main.light.intensity = 0.3f;
         Debug.Msg("boneTransform set", 3);
     }
     else if (isAlreadyOn == false)
     {
         CheatToggles.enableFullbright = !CheatToggles.enableFullbright;
         Debug.Msg("No boneTransform! Fullbright: Toggled " + (CheatToggles.enableFullbright ? "On" : "Off"), 1);
     }
 }

 public static void Disable()
 {
     isAlreadyOn = false;
     Debug.Msg("isAlreadyOn: false", 3);
     Object.Destroy(Main.light);
 }

 private static bool isAlreadyOn = false;

`

some examples from my c# mod menu, I'm not good at c++
 I'm trying to learn c++ by studying your project and making improvements on it. thank you so much for sharing.

**Comment by orcun9988** [comment]
also set player speed won't work too

**Comment by issuimo** [comment]
Thank you for your feedback. We received similar feedback about this issue last week as well. Due to the inconvenience caused by the UnityHack library that the program is based on, the current project cannot be updated further. However, in the next few days, the program will be rewritten using UnityResolve and an attempt will be made to fix these issues.
